"""Evidence Graph data model (§5a.1–5a.2).

Frozen/serialisable dataclasses so a graph can be persisted (e.g. in a job's result)
and reloaded for re-verification. Confidence is a *label set by the Verification
Engine* — never set here — so the model stays a pure record of evidence.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

# --- evidence levels (§5a.2): quality, not count. Higher = stronger. -----
LEVEL_FIELD_DATA = 5     # L5 measured field data / primary datasets
LEVEL_PEER_REVIEWED = 4  # L4 peer-reviewed papers
LEVEL_GOVERNMENT = 3     # L3 government / national-lab reports (NREL, Sandia, …)
LEVEL_TECHNICAL = 2      # L2 technical blogs, manufacturer white papers
LEVEL_FORUM = 1          # L1 forums, Reddit, LinkedIn

_LEVEL_NAMES = {
    5: "L5 field data",
    4: "L4 peer-reviewed",
    3: "L3 government/lab",
    2: "L2 technical blog",
    1: "L1 forum",
}


def level_name(level: int) -> str:
    return _LEVEL_NAMES.get(int(level), f"L{level}")


# --- calculated confidence labels (§5a.3) --------------------------------
CONFIDENCE_HIGH = "HIGH"
CONFIDENCE_MEDIUM = "MEDIUM"
CONFIDENCE_LOW = "LOW"
CONFIDENCE_INSUFFICIENT = "INSUFFICIENT"  # too little evidence to judge
CONFIDENCE_UNVERIFIED = "UNVERIFIED"      # not yet run through the engine
CONFIDENCE_NOT_APPLICABLE = "NOT_APPLICABLE"  # acquire-stop: reasoning never ran (RH2)

# evidence stance toward a claim
STANCE_SUPPORT = "support"
STANCE_CONTRADICT = "contradict"

# evidence origin (report honesty): a verbatim quote from the source vs an
# LLM paraphrase/inference generated by Atlas.
ORIGIN_EXTRACTED = "extracted"
ORIGIN_INFERRED = "inferred"

# Finding lifecycle / freshness (Stage 3B.2+; policies deepen in 3B.3)
FINDING_ACTIVE = "active"
FINDING_CONTESTED = "contested"
FINDING_DEPRECATED = "deprecated"
FINDING_SUPERSEDED = "superseded"
FINDING_ARCHIVED = "archived"

FRESHNESS_CURRENT = "current"
FRESHNESS_AGING = "aging"
FRESHNESS_STALE = "stale"

CLAIM_TYPE_QUANT = "quantitative"
CLAIM_TYPE_PROSE = "prose"
CLAIM_TYPE_HYPOTHESIS = "hypothesis"

# Claim taxonomy (§3B hardening): what *kind* of statement a claim is, so reports
# can synthesize (lead with results/conclusions) and downweight implementation
# details (parameters/config). Reports should rarely headline a parameter.
CLAIM_TYPE_RESULT = "result"            # a measured finding / outcome
CLAIM_TYPE_PARAMETER = "parameter"      # experiment config (q=0.9, 80/20 split, 30-day window)
CLAIM_TYPE_METHOD = "method"            # approach / technique used
CLAIM_TYPE_CONCLUSION = "conclusion"    # authors' concluding statement
CLAIM_TYPE_LIMITATION = "limitation"    # caveat / constraint
CLAIM_TYPE_RECOMMENDATION = "recommendation"
CLAIM_TYPE_COMPARISON = "comparison"    # relative performance ("A outperformed B")
CLAIM_TYPE_OBSERVATION = "observation"  # qualitative observation without a clear result

# Types a synthesis-oriented executive summary should lead with (vs config detail).
HEADLINE_CLAIM_TYPES = (
    CLAIM_TYPE_RESULT,
    CLAIM_TYPE_CONCLUSION,
    CLAIM_TYPE_COMPARISON,
    CLAIM_TYPE_LIMITATION,
)


@dataclass(frozen=True, slots=True)
class Source:
    """A place evidence came from (a paper, report, dataset, page)."""

    id: str
    title: str = ""
    url: str = ""
    evidence_level: int = LEVEL_TECHNICAL
    kind: str = ""  # e.g. "peer_reviewed", "government", "field_data", "blog"
    # Bibliographic extras (Stage 3.2 / D32.7) — keep even when full text fails.
    doi: str = ""
    citation: str = ""
    authors: tuple[str, ...] = ()
    year: int | None = None
    venue: str = ""

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "title": self.title,
            "url": self.url,
            "evidence_level": self.evidence_level,
            "level_name": level_name(self.evidence_level),
            "kind": self.kind,
            "doi": self.doi,
            "citation": self.citation,
            "authors": list(self.authors),
            "year": self.year,
            "venue": self.venue,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Source":
        authors = data.get("authors") or ()
        if isinstance(authors, str):
            authors = tuple(a.strip() for a in authors.split(";") if a.strip())
        else:
            authors = tuple(str(a) for a in authors)
        year = data.get("year")
        return cls(
            id=str(data["id"]),
            title=data.get("title", "") or "",
            url=data.get("url", "") or "",
            evidence_level=int(data.get("evidence_level", LEVEL_TECHNICAL)),
            kind=data.get("kind", "") or "",
            doi=data.get("doi", "") or "",
            citation=data.get("citation", "") or "",
            authors=authors,
            year=int(year) if year is not None and str(year).strip() != "" else None,
            venue=data.get("venue", "") or "",
        )


@dataclass(frozen=True, slots=True)
class EvidenceItem:
    """One source's contribution to a claim (§5a.1)."""

    source_id: str
    evidence_level: int
    extracted_value: float | None = None
    unit: str = ""
    snippet: str = ""
    locator: str = ""  # page/section/anchor
    stance: str = STANCE_SUPPORT
    # Provenance of the extraction (§3B report honesty): whether the snippet is a
    # verbatim quote from the source ("extracted") or an LLM paraphrase/inference
    # ("inferred"). Reports must never present an inference as a direct quote.
    origin: str = ORIGIN_EXTRACTED

    @property
    def supports(self) -> bool:
        return self.stance != STANCE_CONTRADICT

    @property
    def inferred(self) -> bool:
        return self.origin == ORIGIN_INFERRED

    def as_dict(self) -> dict[str, Any]:
        return {
            "source_id": self.source_id,
            "evidence_level": self.evidence_level,
            "level_name": level_name(self.evidence_level),
            "extracted_value": self.extracted_value,
            "unit": self.unit,
            "snippet": self.snippet,
            "locator": self.locator,
            "stance": self.stance,
            "origin": self.origin,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EvidenceItem":
        return cls(
            source_id=str(data.get("source_id", "")),
            evidence_level=int(data.get("evidence_level", LEVEL_TECHNICAL)),
            extracted_value=(
                float(data["extracted_value"])
                if data.get("extracted_value") is not None
                else None
            ),
            unit=data.get("unit", ""),
            snippet=data.get("snippet", ""),
            locator=data.get("locator", ""),
            stance=data.get("stance", STANCE_SUPPORT),
            origin=data.get("origin", ORIGIN_EXTRACTED),
        )


@dataclass(frozen=True, slots=True)
class ClaimValue:
    number: float
    unit: str = ""
    kind: str = ""  # e.g. "annual_mean"

    def as_dict(self) -> dict[str, Any]:
        return {"number": self.number, "unit": self.unit, "kind": self.kind}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ClaimValue":
        return cls(
            number=float(data["number"]),
            unit=data.get("unit", ""),
            kind=data.get("kind", ""),
        )


@dataclass
class Claim:
    """A statement Atlas may assert, with graded evidence and a *calculated* confidence."""

    id: str
    statement: str
    value: ClaimValue | None = None
    evidence: list[EvidenceItem] = field(default_factory=list)
    confidence: str = CONFIDENCE_UNVERIFIED
    confidence_score: float = 0.0
    convergence: float | None = None
    last_verified: str | None = None
    verification_method: str = ""
    reasoning_trace: list[str] = field(default_factory=list)
    claim_type: str = ""  # taxonomy: result | parameter | method | conclusion | …

    @property
    def supporting(self) -> list[EvidenceItem]:
        return [e for e in self.evidence if e.supports]

    @property
    def contradicting(self) -> list[EvidenceItem]:
        return [e for e in self.evidence if not e.supports]

    def supporting_values(self) -> list[float]:
        return [e.extracted_value for e in self.supporting if e.extracted_value is not None]

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "statement": self.statement,
            "value": self.value.as_dict() if self.value else None,
            "confidence": self.confidence,
            "confidence_score": round(self.confidence_score, 3),
            "convergence": (
                round(self.convergence, 3) if self.convergence is not None else None
            ),
            "last_verified": self.last_verified,
            "verification_method": self.verification_method,
            "reasoning_trace": list(self.reasoning_trace),
            "claim_type": self.claim_type,
            "supporting_sources": [e.as_dict() for e in self.supporting],
            "contradicting_sources": [e.as_dict() for e in self.contradicting],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Claim":
        value = data.get("value")
        # Accept both the flat `evidence` list and split supporting/contradicting.
        items: list[EvidenceItem] = []
        if "evidence" in data:
            items = [EvidenceItem.from_dict(e) for e in data["evidence"]]
        else:
            for e in data.get("supporting_sources", []):
                items.append(EvidenceItem.from_dict({**e, "stance": STANCE_SUPPORT}))
            for e in data.get("contradicting_sources", []):
                items.append(EvidenceItem.from_dict({**e, "stance": STANCE_CONTRADICT}))
        return cls(
            id=str(data.get("id", "")),
            statement=data.get("statement", ""),
            value=ClaimValue.from_dict(value) if value else None,
            evidence=items,
            claim_type=data.get("claim_type", "") or "",
        )


@dataclass
class Finding:
    """Durable synthesized knowledge unit (Stage 3B.2).

    Evidence/Claim remain transient; Findings are the durable home
    (``knowledge.findings``). Claim-shaped keys in ``as_dict`` keep reports working
    when findings are preferred over raw claims (A3B.9).
    """

    id: str
    statement: str
    canonical_id: str = ""
    revision: int = 1
    value: ClaimValue | None = None
    evidence: list[EvidenceItem] = field(default_factory=list)
    confidence: str = CONFIDENCE_UNVERIFIED
    confidence_score: float = 0.0
    claim_type: str = CLAIM_TYPE_PROSE
    status: str = FINDING_ACTIVE
    freshness: str = FRESHNESS_CURRENT
    quality: dict[str, Any] = field(default_factory=dict)
    provenance: dict[str, Any] = field(default_factory=dict)
    domain: str = "research"
    supersedes: str | None = None
    superseded_by: str | None = None
    last_verified: str | None = None
    source_claim_ids: list[str] = field(default_factory=list)

    @property
    def supporting(self) -> list[EvidenceItem]:
        return [e for e in self.evidence if e.supports]

    @property
    def contradicting(self) -> list[EvidenceItem]:
        return [e for e in self.evidence if not e.supports]

    def as_dict(self) -> dict[str, Any]:
        """Claim-compatible export plus Finding identity / quality fields."""
        return {
            "id": self.id,
            "canonical_id": self.canonical_id,
            "revision": self.revision,
            "statement": self.statement,
            "value": self.value.as_dict() if self.value else None,
            "claim_type": self.claim_type,
            "confidence": self.confidence,
            "confidence_score": round(self.confidence_score, 3),
            "status": self.status,
            "freshness": self.freshness,
            "quality": dict(self.quality),
            "provenance": dict(self.provenance),
            "domain": self.domain,
            "supersedes": self.supersedes,
            "superseded_by": self.superseded_by,
            "last_verified": self.last_verified,
            "source_claim_ids": list(self.source_claim_ids),
            "supporting_sources": [e.as_dict() for e in self.supporting],
            "contradicting_sources": [e.as_dict() for e in self.contradicting],
            "convergence": None,
            "verification_method": "synthesizer:v1",
            "reasoning_trace": [],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Finding":
        value = data.get("value")
        items: list[EvidenceItem] = []
        if "evidence" in data:
            items = [EvidenceItem.from_dict(e) for e in data["evidence"]]
        else:
            for e in data.get("supporting_sources", []):
                items.append(EvidenceItem.from_dict({**e, "stance": STANCE_SUPPORT}))
            for e in data.get("contradicting_sources", []):
                items.append(EvidenceItem.from_dict({**e, "stance": STANCE_CONTRADICT}))
        quality = data.get("quality") or {}
        if not isinstance(quality, dict):
            quality = {}
        provenance = data.get("provenance") or {}
        if not isinstance(provenance, dict):
            provenance = {}
        return cls(
            id=str(data.get("id", "")),
            statement=data.get("statement", "") or "",
            canonical_id=str(data.get("canonical_id", "") or ""),
            revision=max(1, int(data.get("revision", 1) or 1)),
            value=ClaimValue.from_dict(value) if value else None,
            evidence=items,
            confidence=str(data.get("confidence", CONFIDENCE_UNVERIFIED)),
            confidence_score=float(data.get("confidence_score", 0) or 0),
            claim_type=str(data.get("claim_type", CLAIM_TYPE_PROSE) or CLAIM_TYPE_PROSE),
            status=str(data.get("status", FINDING_ACTIVE) or FINDING_ACTIVE),
            freshness=str(data.get("freshness", FRESHNESS_CURRENT) or FRESHNESS_CURRENT),
            quality=dict(quality),
            provenance=dict(provenance),
            domain=str(data.get("domain", "research") or "research"),
            supersedes=(str(data["supersedes"]) if data.get("supersedes") else None),
            superseded_by=(
                str(data["superseded_by"]) if data.get("superseded_by") else None
            ),
            last_verified=data.get("last_verified"),
            source_claim_ids=[str(x) for x in (data.get("source_claim_ids") or [])],
        )


class EvidenceGraph:
    """A container of sources + claims (§5a). Serialisable for persistence/re-verify."""

    def __init__(self) -> None:
        self.sources: dict[str, Source] = {}
        self.claims: dict[str, Claim] = {}

    def add_source(self, source: Source) -> Source:
        self.sources[source.id] = source
        return source

    def add_claim(self, claim: Claim) -> Claim:
        self.claims[claim.id] = claim
        return claim

    def get_claim(self, claim_id: str) -> Claim | None:
        return self.claims.get(claim_id)

    def as_dict(self) -> dict[str, Any]:
        return {
            "sources": [s.as_dict() for s in self.sources.values()],
            "claims": [c.as_dict() for c in self.claims.values()],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EvidenceGraph":
        graph = cls()
        for s in data.get("sources", []):
            graph.add_source(Source.from_dict(s))
        for c in data.get("claims", []):
            graph.add_claim(Claim.from_dict(c))
        return graph
